gcc -Wall -D RPI -shared -o libbm4.so -fPIC \
	Arduino.cpp \
	device.cpp \
	actuator.cpp \
	sensor.cpp \
	beeper.cpp \
	buzzer.cpp \
	dcmotor.cpp \
	dht.cpp \
	ds18.cpp \
	hcsr04.cpp \
	hcsr501.cpp \
	json.cpp \
	led.cpp \
	mfrc522.cpp \
	pn532.cpp \
	rgbled.cpp \
	sound.cpp \
	sqlclient.cpp \
	switch.cpp \
	-L/usr/local/include -lbcm2835
